---
- name: Install Hadoop dependencies.
  apk:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - alpine-sdk
    - procps
    - openjdk8
    - autoconf
    - ncurses
    - automake
    - libtool
    - fts-dev
    - curl-dev
    - apr-dev
    - cyrus-sasl-dev
    - unzip
    - tar
    - gzip
    - bzip2
    - bash
- name: Copy the relevant rc files to /root.
  copy:
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
  with_items:
    - src: vimrc
      dest: /root/.vimrc
    - src: bashrc
      dest: /root/.bashrc
    - src: wakatime.cfg
      dest: /root/.wakatime.cfg
    - src: git-completion.bash
      dest: /root/.git-completion.bash
- name: Create the /opt directory.
  file:
    state: directory
    dest: /opt
- name: Download and untar the hadoop binaries.
  get_url:
    url: http://www-eu.apache.org/dist/hadoop/common/hadoop-3.1.0/hadoop-3.1.0.tar.gz
    dest: /opt/hadoop.tar.gz
- name: Untar the Hadoop binary.
  unarchive:
    src: /opt/hadoop.tar.gz
    dest: /opt
- name: Make sure there is no existing directory.
  file:
    dest: /opt/hadoop
    state: absent
- name: Move hadoop to its new home.
  shell: mv -v /opt/hadoop-3.1.0 /opt/hadoop
...
