---
- name: Install Hadoop dependencies.
  apk:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - alpine-sdk
    - procps
    - openjdk8
    - autoconf
    - ncurses
    - automake
    - libtool
    - fts-dev
    - curl-dev
    - apr-dev
    - cyrus-sasl-dev
    - unzip
    - tar
    - gzip
    - bzip2
    - bash
- name: Copy the relevant rc files to /root.
  copy:
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
  with_items:
    - src: vimrc
      dest: /root/.vimrc
    - src: bashrc
      dest: /root/.bashrc
    - src: wakatime.cfg
      dest: /root/.wakatime.cfg
    - src: git-completion.bash
      dest: /root/.git-completion.bash
- name: Create the /opt directory.
  file:
    state: directory
    dest: /opt

...
